### PR TITLE
Build Ubuntu Packages

### PR DESCRIPTION
**Pull request by gdevenyi**
Automated zipfile generation for 18.04 and 20.04

In theory doable for other Centos environments.

### CODE REVIEW

**Comment by gdevenyi** [comment]
This code would be updated for when newer "releases" of the package are tagged, and the resulting zip files could be attached on the release in github.

**Review by frankyeh — APPROVED** [review]

**Comment by frankyeh** [comment]
I just updated DSI Studio to use g++9. You may test if the Dockerfile still works.

**Comment by frankyeh** [comment]
Thanks for showing me how to build Ubuntu 1804 and 2004. I learned a lot.

**Comment by gdevenyi** [comment]
I would suggest you run these two build.sh files and upload the files on this release: https://github.com/frankyeh/DSI-Studio/releases/tag/2021_06

I will investigate the updates on master.

**Comment by frankyeh** [comment]
Thank for the instructions. Building it now...

**Comment by mohammadhadiarabi** [comment]
Thank you for this. I did step by step and when run ./dsi_studio , I see this error:
./dsi_studio: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./dsi_studio)

**Comment by mohammadhadiarabi** [comment]
and when fixed this problem, I encountered with a new error:
Cannot mix incompatible Qt library (version 0x50c00) with this library (version 0x50c08)

**Comment by gdevenyi** [comment]
@mohammadhadiarabi please open an issue and provide full details of your system. Please note the README accompanying each set of build instructions.

**Comment by frankyeh** [comment]
@mohammadhadiarabi <https://github.com/mohammadhadiarabi>
I have built binary here:
https://github.com/frankyeh/DSI-Studio/releases/tag/2021_06
and you can see if it has the same error

**Comment by mohammadhadiarabi** [comment]
Thank you for your replies. Unfutenly see this error:
Cannot mix incompatible Qt library (version 0x50c00) with this library (version 0x50c08)
I before installed the previous version in Linux. Should I remove it completely?

**Comment by frankyeh** [comment]
Yes, likely the Qt library installed is not compatible.

**Comment by gdevenyi** [comment]
Please see, https://github.com/frankyeh/DSI-Studio/tree/master/build_packages/ubuntu_1804/README.md for installation dependencies.

**Pull request merged**
